### PR TITLE
Fixes to format_csv function including (1) updating function argument…

### PR DESCRIPTION
**Pull request by scelmendorf**
… names in documentation, (2) subsetting locations to single unique lat/long, (3) unquoting in subsets, (4) renaming phenphase to phenophase_obs so this object does not overwrite the function argument phenophase, (5) correcting logic on missing phenophase argument (6) implementing filtering by phenophase, (7) updating daymet arguments from quiet to silent

### CODE REVIEW

**Comment by scelmendorf** [comment]
@khufkens here's updates I made to format_csv - hope it's helpful more generally. One slight (though very small) annoying issue still is that if you try to prep/edit a csv in excel and then run this function, excel complains re the column named 'ID' and won't open the file (it thinks it's a sylk file - see here:https://www.drupal.org/project/csv_serialization/issues/2802081). There's better spreadsheet editors out there and likely people won't be making the input files by hand in excel anyhow...it's just something I discovered trying to make a quick test dataset. One could consider renaming ID to site or something so that it's more excel-friendly if you wanted to.

**Comment by khufkens** [comment]
Hi @scelmendorf, could you do me a favour and run devtools::document() to update the documentation of the package and push again? This will make sure things are also well documented.

**Comment by scelmendorf** [comment]
@khufkens done (I think?) - should automagically go into this PR since it's not merged yet? Sorry I forgot to do that the first time!

**Comment by khufkens** [comment]
Yes this was ingested in this PR, thanks!

**Pull request merged**
